// 语义角色词表：与 Citrine 种子的 semantic.tokens.json 对齐的用途名。draft-tokens 用它列缺口，check-contrast 用它配对，
// render-token-board 用它分组。tier：core = 产品 UI 的基础集合；extended = 有证据再填；shell = 中后台壳层（侧栏 / 表格 / 图表）。
// 哪些角色「必须处理」不由 tier 单独决定，由系统类型（types.mjs / assets/types）决定——通用网站不必发明状态色与危险色，中后台则连 shell 一起要。
// dark = 暗色 Theme 通常需要覆写（true）还是随 Core 不变（false）。references/semantic-roles.md 是这份表的人类版；改一处要同步另一处。

export const ROLE_GROUPS = [
  ["bg", "底色"],
  ["text", "文字"],
  ["action", "操作面"],
  ["border", "边线"],
  ["focus", "焦点"],
  ["status", "状态"],
  ["brand", "品牌"],
  ["icon", "图标"],
  ["chart", "图表"],
  ["data", "数据"],
  ["control", "控件"],
  ["space", "留白"],
  ["font", "字体"],
  ["typography", "字号阶梯"],
  ["layout", "布局"],
  ["elevation", "层级阴影"],
  ["motion", "动效"],
  ["opacity", "透明度"],
  ["layer", "z 层"],
  ["table", "表格"]
];

const role = (path, type, tier, group, zh, hint, dark = false) => ({ dark, group, hint, path, tier, type, zh });

export const ROLES = [
  // 底色
  role("color.bg.page", "color", "core", "bg", "页面底", "body / html 背景色", true),
  role("color.bg.surface", "color", "core", "bg", "卡片 / 面板表面", "卡片、区块最常见的背景色（亮色站通常是白）", true),
  role("color.bg.subtle", "color", "core", "bg", "浅分区底", "表头、分区、次级容器的浅底，比 surface 深一档", true),
  role("color.bg.hover", "color", "core", "bg", "悬停底", "导航项 / 次要按钮 hover 后的底色（悬停探针）", true),
  role("color.bg.input", "color", "core", "bg", "输入框底", "input / textarea / select 背景色", true),
  role("color.bg.elevated", "color", "core", "bg", "浮层表面", "下拉、弹窗表面；暗色下要比 surface 亮一档", true),
  role("color.bg.overlay", "color", "core", "bg", "弹窗遮罩", "覆盖全页的半透明深色底", true),
  role("color.bg.inverse", "color", "core", "bg", "反色底", "Tooltip / 深色 Toast / 深色页脚的底", true),
  role("color.bg.selected", "color", "extended", "bg", "选中底（小面积）", "筹码、批量条、当前导航项的底", true),
  role("color.bg.selected-subtle", "color", "extended", "bg", "选中底（大面积）", "表格选中行、列表选中项", true),
  role("color.bg.selected-hover", "color", "extended", "bg", "选中 + 悬停", "已选中项再被悬停", true),
  role("color.bg.brand", "color", "extended", "bg", "大面积品牌面", "登录页品牌区、欢迎横幅", false),
  role("color.bg.skeleton", "color", "extended", "bg", "骨架屏底", "加载占位块", true),
  role("color.bg.skeleton-highlight", "color", "extended", "bg", "骨架屏流光", "骨架屏高亮扫过的颜色", true),
  role("color.bg.readonly", "color", "extended", "bg", "只读字段底", "可读不可改的字段", true),
  role("color.bg.mask", "color", "extended", "bg", "局部加载遮罩", "盖在一块卡片 / 表格上的半透明底", true),
  role("color.bg.sidebar", "color", "shell", "bg", "侧栏底", "中后台侧栏背景", true),
  role("color.bg.sidebar-hover", "color", "shell", "bg", "侧栏项悬停", "", true),
  role("color.bg.sidebar-selected", "color", "shell", "bg", "侧栏当前项", "", true),
  // 文字
  role("color.text.primary", "color", "core", "text", "正文 / 标题", "承载最多文字量的深色文字", true),
  role("color.text.secondary", "color", "core", "text", "次要文字", "说明、副标题，比正文浅一档", true),
  role("color.text.muted", "color", "core", "text", "弱化文字", "帮助文字、时间戳；仍需 ≥ 4.5:1", true),
  role("color.text.placeholder", "color", "core", "text", "占位符", "input::placeholder 的颜色", true),
  role("color.text.inverse", "color", "core", "text", "反色文字", "落在 bg.inverse / 深底上的文字", true),
  role("color.text.on-primary", "color", "core", "text", "主按钮文字", "主按钮上的文字色", false),
  role("color.text.on-danger", "color", "core", "text", "危险按钮文字", "", false),
  role("color.text.link", "color", "core", "text", "内容型链接", "正文 / 表格里的 a 颜色", true),
  role("color.text.link-hover", "color", "core", "text", "链接悬停", "悬停探针里 a 的 color 变化", true),
  role("color.text.danger", "color", "core", "text", "危险文字", "删除项、危险链接（暗色下要比填充色亮）", true),
  role("color.text.brand", "color", "extended", "text", "品牌大字", "只允许 ≥ 20px 的展示性文字用品牌色", true),
  role("color.text.selected", "color", "extended", "text", "选中文字", "排序激活、当前项文字", true),
  role("color.text.on-selected", "color", "extended", "text", "选中块上的文字", "落在 action.selected 上的文字", true),
  role("color.text.on-brand", "color", "extended", "text", "品牌面上的文字", "落在 bg.brand 上的文字", false),
  role("color.text.sidebar", "color", "shell", "text", "侧栏文字", "", true),
  role("color.text.sidebar-strong", "color", "shell", "text", "侧栏强调文字", "", true),
  role("color.text.sidebar-muted", "color", "shell", "text", "侧栏弱化文字", "", true),
  role("color.text.sidebar-selected", "color", "shell", "text", "侧栏当前项文字", "", true),
  // 操作面
  role("color.action.primary", "color", "core", "action", "主按钮填充", "最显眼的彩色按钮背景", false),
  role("color.action.primary-hover", "color", "core", "action", "主按钮悬停", "悬停探针；无证据时同色系深一档", false),
  role("color.action.primary-active", "color", "core", "action", "主按钮按下", "同 hover 或再深一档", false),
  role("color.action.secondary-hover", "color", "core", "action", "次要按钮悬停底", "描边按钮 hover 的底", true),
  role("color.action.danger", "color", "core", "action", "危险按钮填充", "红色实底按钮；亮暗都保持深红", false),
  role("color.action.danger-hover", "color", "core", "action", "危险按钮悬停", "", false),
  role("color.action.danger-active", "color", "core", "action", "危险按钮按下", "", false),
  role("color.action.selected", "color", "extended", "action", "选中态填充", "分段选择器 / 视图切换当前项的底（Citrine 用深黑反转，不用品牌色）", true),
  role("color.action.quiet", "color", "extended", "action", "文字按钮静息底", "quiet 按钮的浅底", true),
  role("color.action.quiet-hover", "color", "extended", "action", "文字按钮悬停底", "", true),
  // 边线 / 焦点
  role("color.border.default", "color", "core", "border", "普通边线", "出现最多的 border-color", true),
  role("color.border.strong", "color", "core", "border", "实边线", "比 default 深一档：勾选框、上传虚线", true),
  role("color.border.input", "color", "core", "border", "输入框边线", "input 的 border-color", true),
  role("color.border.focus", "color", "core", "border", "焦点边线", "焦点探针 / :focus-visible 规则里的边线或 outline 色", true),
  role("color.border.current", "color", "extended", "border", "当前指示线", "标签页下划线等", true),
  role("color.border.sidebar", "color", "shell", "border", "侧栏边线", "", true),
  role("color.focus.ring", "color", "core", "focus", "焦点环颜色", "focus 时 box-shadow / outline 的颜色（常带透明度）", true),
  // 状态
  role("color.status.success", "color", "core", "status", "成功文字色", "根变量 --success / 徽标类名 success", true),
  role("color.status.success-bg", "color", "core", "status", "成功浅底", "", true),
  role("color.status.warning", "color", "core", "status", "警示文字色", "橙 / 黄族；与品牌色靠色相分开", true),
  role("color.status.warning-bg", "color", "core", "status", "警示浅底", "", true),
  role("color.status.error", "color", "core", "status", "错误文字色", "红族", true),
  role("color.status.error-bg", "color", "core", "status", "错误浅底", "", true),
  role("color.status.info", "color", "core", "status", "信息文字色", "蓝 / 青族", true),
  role("color.status.info-bg", "color", "core", "status", "信息浅底", "", true),
  role("color.status.neutral", "color", "core", "status", "中性状态文字色", "草稿 / 已停用", true),
  role("color.status.neutral-bg", "color", "core", "status", "中性状态浅底", "", true),
  // 品牌 / 图标 / 控件
  role("color.brand.indicator", "color", "extended", "brand", "品牌指示条", "侧栏当前项左侧竖条、数据卡左描边", false),
  role("color.icon.default", "color", "core", "icon", "独立图标默认色", "工具栏 / 表格操作图标；≥ 3:1", true),
  role("color.icon.muted", "color", "core", "icon", "装饰性图标", "", true),
  role("color.icon.brand", "color", "extended", "icon", "品牌插图描边", "two-tone 图标描边", true),
  role("color.icon.two-tone", "color", "extended", "icon", "品牌插图填充", "", false),
  role("color.control.knob", "color", "extended", "control", "开关滑块", "亮暗都保持白", false),
  // 图表 / 数据
  role("color.chart.1", "color", "shell", "chart", "分类色 1", "品牌色领衔；shadcn 站点看根变量 --chart-1…5", true),
  role("color.chart.2", "color", "shell", "chart", "分类色 2", "", true),
  role("color.chart.3", "color", "shell", "chart", "分类色 3", "", true),
  role("color.chart.4", "color", "shell", "chart", "分类色 4", "", true),
  role("color.chart.5", "color", "shell", "chart", "分类色 5", "", true),
  role("color.chart.6", "color", "shell", "chart", "分类色 6", "", true),
  role("color.chart.area", "color", "shell", "chart", "面积填充", "半透明，网格线要透得出来", false),
  role("color.data.increase", "color", "shell", "data", "涨", "公司约定：涨绿跌红或红涨绿跌，只改这两个别名", true),
  role("color.data.decrease", "color", "shell", "data", "跌", "", true),
  role("color.data.inactive", "color", "shell", "data", "非进行中的数据填充", "已结束的进度条", true),
  // 留白 / 字体 / 字号
  role("space.inline", "dimension", "core", "space", "行内相邻元素间距", "最常见的小 gap（≤ 12px）", false),
  role("space.stack", "dimension", "core", "space", "块与块的纵向间距", "卡片之间 / 网格 gap（12～32px）", false),
  role("space.gutter", "dimension", "core", "space", "内容区四周留白", "section / 容器的左右 padding", false),
  role("space.card", "dimension", "core", "space", "卡片内边距", "卡片 / 弹窗 / 抽屉的 padding", false),
  role("font.family.body", "fontFamily", "core", "font", "正文字体栈", "body 的 font-family", false),
  role("font.family.code", "fontFamily", "extended", "font", "等宽字体栈", "code / pre / 单号", false),
  role("font.family.heading", "fontFamily", "extended", "font", "标题字体栈", "标题字体与正文不同时才有", false),
  role("text.caption.size", "dimension", "core", "typography", "最小字号", "正文类文字的下限（中文一般 ≥ 12px）", false),
  role("text.small.size", "dimension", "core", "typography", "小字", "", false),
  role("text.body-sm.size", "dimension", "core", "typography", "小正文", "", false),
  role("text.body.size", "dimension", "core", "typography", "正文", "承载最多文字量的字号", false),
  role("text.body.line-height", "number", "core", "typography", "正文行高", "", false),
  role("text.title-sm.size", "dimension", "core", "typography", "小标题", "", false),
  role("text.title.size", "dimension", "core", "typography", "标题", "", false),
  role("text.heading.size", "dimension", "core", "typography", "页头标题", "h2 一级", false),
  role("text.heading.line-height", "number", "core", "typography", "标题行高", "紧行高", false),
  role("text.display.size", "dimension", "extended", "typography", "数据大字 / 展示字号", "h1 / 统计数字", false),
  role("text.display.weight", "fontWeight", "extended", "typography", "数据大字字重", "", false),
  role("text.display.line-height", "number", "extended", "typography", "数据大字行高", "", false),
  role("text.display.tracking", "dimension", "extended", "typography", "数据大字字距", "负字距", false),
  role("text.hero.size", "dimension", "extended", "typography", "结果页 / 登录页大字", "", false),
  role("text.hero.line-height", "number", "extended", "typography", "大字行高", "", false),
  role("text.paragraph.line-height", "number", "extended", "typography", "成段说明行高", "", false),
  role("text.weight.label", "fontWeight", "core", "typography", "标签类字重", "按钮 / 表头 / 表单标签", false),
  role("text.weight.strong", "fontWeight", "core", "typography", "强调字重", "", false),
  role("text.weight.brand", "fontWeight", "extended", "typography", "品牌字重", "", false),
  role("text.tracking.caps", "dimension", "extended", "typography", "全大写小字字距", "", false),
  role("text.link.decoration", "string", "extended", "typography", "链接装饰", "underline / none", false),
  role("text.numeric.variant", "string", "extended", "typography", "数字变体", "tabular-nums", false),
  // 控件 / 图标尺寸 / 布局
  role("control.height.sm", "dimension", "core", "control", "小控件高", "小按钮、分页项", false),
  role("control.height.md", "dimension", "core", "control", "默认控件高", "按钮、输入框共用", false),
  role("control.height.lg", "dimension", "core", "control", "大控件高", "登录按钮、触屏", false),
  role("control.height.xs", "dimension", "extended", "control", "行内胶囊高", "操作胶囊、状态胶囊", false),
  role("control.hit-min", "dimension", "extended", "control", "图标控件最小命中区", "≥ 24px", false),
  role("icon.size.xs", "dimension", "extended", "control", "图标 xs", "", false),
  role("icon.size.sm", "dimension", "extended", "control", "图标 sm", "", false),
  role("icon.size.md", "dimension", "core", "control", "图标默认尺寸", "出现最多的 svg 边长", false),
  role("icon.size.lg", "dimension", "extended", "control", "图标 lg", "", false),
  role("icon.size.xl", "dimension", "extended", "control", "图标 xl", "", false),
  role("icon.library", "string", "extended", "control", "图标库", "lucide / IconPark / …", false),
  role("icon.stroke.width", "number", "extended", "control", "图标描边", "svg stroke-width", false),
  role("layout.topbar.height", "dimension", "core", "layout", "顶栏高度", "header 高度", false),
  role("layout.sidebar.width", "dimension", "shell", "layout", "侧栏宽度", "", false),
  role("layout.sidebar.collapsed-width", "dimension", "shell", "layout", "侧栏折叠宽度", "", false),
  role("layout.container.max-width", "dimension", "extended", "layout", "内容容器最大宽", "居中容器的 max-width", false),
  role("layout.breakpoint.mobile", "dimension", "core", "layout", "手机断点", "样式表 @media 里最常见的小断点", false),
  role("layout.breakpoint.narrow", "dimension", "core", "layout", "窄屏断点", "", false),
  role("layout.root.font-size", "dimension", "extended", "layout", "html 根字号", "vw 缩放的 rem 站点才有：桌面视口下 html 的 font-size，所有 rem 尺寸的基准", false),
  role("layout.form.label-width", "dimension", "shell", "layout", "横向表单标签列宽", "", false),
  role("layout.form.max-width", "dimension", "shell", "layout", "单列表单最大宽", "", false),
  role("layout.modal.width.sm", "dimension", "shell", "layout", "确认弹窗宽", "", false),
  role("layout.modal.width.md", "dimension", "shell", "layout", "表单弹窗宽", "", false),
  role("layout.drawer.width", "dimension", "shell", "layout", "抽屉宽", "", false),
  role("border.width.default", "dimension", "core", "border", "普通边线宽", "最常见的 border-width", false),
  role("border.width.control", "dimension", "extended", "border", "小控件边线宽", "", false),
  role("border.width.active", "dimension", "extended", "border", "选中下划线 / 焦点外框宽", "", false),
  role("border.width.indicator", "dimension", "shell", "border", "指示条宽", "", false),
  role("focus.ring.width", "dimension", "core", "focus", "焦点环粗细", "focus 时 box-shadow spread 或 outline-width", false),
  // 阴影 / 动效 / 透明度 / 层级 / 表格
  role("elevation.card.y", "dimension", "core", "elevation", "卡片阴影 y", "写法：box-shadow: 0 var(--elevation-card-y) var(--elevation-card-blur) var(--elevation-card-color)", false),
  role("elevation.card.blur", "dimension", "core", "elevation", "卡片阴影模糊", "", false),
  role("elevation.card.color", "color", "core", "elevation", "卡片阴影色", "暗色下常改为透明，靠边线分层", true),
  role("elevation.popover.y", "dimension", "extended", "elevation", "浮层阴影 y", "", false),
  role("elevation.popover.blur", "dimension", "extended", "elevation", "浮层阴影模糊", "", false),
  role("elevation.popover.color", "color", "extended", "elevation", "浮层阴影色", "", true),
  role("elevation.modal.y", "dimension", "extended", "elevation", "弹窗阴影 y", "", false),
  role("elevation.modal.blur", "dimension", "extended", "elevation", "弹窗阴影模糊", "", false),
  role("elevation.modal.color", "color", "extended", "elevation", "弹窗阴影色", "", true),
  role("motion.duration.fast", "duration", "core", "motion", "即时反馈时长", "hover / active", false),
  role("motion.duration.normal", "duration", "core", "motion", "浮层出现时长", "", false),
  role("motion.duration.slow", "duration", "core", "motion", "弹窗 / 抽屉时长", "", false),
  role("motion.easing.standard", "cubicBezier", "core", "motion", "标准缓动", "最常见的 timing-function", false),
  role("motion.easing.enter", "cubicBezier", "extended", "motion", "进场缓动", "ease-out 类", false),
  role("motion.easing.exit", "cubicBezier", "extended", "motion", "退场缓动", "ease-in 类", false),
  role("opacity.disabled", "number", "core", "opacity", "禁用态透明度", "带 disabled 的元素 opacity", false),
  role("layer.sticky", "number", "core", "layer", "吸顶层", "z-index 最小的一档", false),
  role("layer.dropdown", "number", "core", "layer", "下拉 / Tooltip 层", "", false),
  role("layer.modal", "number", "core", "layer", "弹窗层", "", false),
  role("layer.toast", "number", "core", "layer", "通知层", "最高", false),
  role("table.cell.padding-y", "dimension", "shell", "table", "单元格纵向内边距", "td 的 padding-top", false),
  role("table.cell.padding-x", "dimension", "shell", "table", "单元格横向内边距", "", false)
];

export const ROLE_BY_PATH = new Map(ROLES.map((entry) => [entry.path, entry]));

// 系统类型（哪些角色必须处理 / 允许推断）是数据，见 scripts/lib/types.mjs 与 assets/types/<id>/type.json。

/**
 * 旧规范 → 新 token 的角色对照（design-system-adopter「更换现有规范」剧本在 settle 阶段用它起草决策文件）。
 * 与 Citrine 的 migration/roles.json 同一形状：role / to / var / properties / hints / note。hints 是旧变量名与注释里常见的字样——
 * 这里只放通用词，旧系统独有的色值由维护者在生成后补进去。to 必须是本系统 semantic 里真实存在的路径，生成时会过滤。
 */
export const MIGRATION_ROLES = [
  { hints: ["text", "font-color", "foreground", "正文", "主文字", "#333", "#303133", "#1f2937"], note: "文字三档按角色对应，不按色值找最接近的灰。", properties: ["color"], role: "正文色", to: "color.text.primary" },
  { hints: ["secondary", "subtitle", "次要", "#606266", "#4b5563"], note: "", properties: ["color"], role: "次要文字", to: "color.text.secondary" },
  { hints: ["muted", "disabled-text", "placeholder-text", "弱化", "辅助", "#909399", "#999", "#9ca3af"], note: "弱化文字仍要 ≥ 4.5:1；占位符另有 color.text.placeholder。", properties: ["color"], role: "弱化文字", to: "color.text.muted" },
  { hints: ["placeholder", "占位"], note: "", properties: ["color"], role: "占位符", to: "color.text.placeholder" },
  { hints: ["border", "divider", "分割线", "边线", "#dcdfe6", "#e4e7ed", "#e5e7eb"], note: "输入框边线用 color.border.input。", properties: ["border-color", "border", "outline-color", "box-shadow"], role: "边线", to: "color.border.default" },
  { hints: ["input-border", "输入框边"], note: "", properties: ["border-color", "border"], role: "输入框边线", to: "color.border.input" },
  { hints: ["page-bg", "body-bg", "页面底", "#f5f7fa", "#f0f2f5", "#f9fafb"], note: "", properties: ["background", "background-color"], role: "页面底", to: "color.bg.page" },
  { hints: ["section", "表头底", "分区", "muted-bg", "#f5f5f5"], note: "表头、浅分区。", properties: ["background", "background-color"], role: "分区底", to: "color.bg.subtle" },
  { hints: ["card", "white", "surface", "#fff", "#ffffff"], note: "同一个旧白值在新系统里可能是三个语义：卡片 bg.surface、输入框 bg.input、浮层 bg.elevated。", properties: ["background", "background-color"], role: "卡片白", to: "color.bg.surface" },
  { hints: ["input-bg", "输入框底"], note: "", properties: ["background", "background-color"], role: "输入框底", to: "color.bg.input" },
  { hints: ["popover", "dialog-bg", "dropdown-bg", "浮层", "弹窗"], note: "", properties: ["background", "background-color"], role: "浮层底", to: "color.bg.elevated" },
  { hints: ["hover-bg", "hover", "悬停"], note: "", properties: ["background", "background-color"], role: "悬停底", to: "color.bg.hover" },
  { hints: ["brand", "primary", "主色", "accent"], note: "一个旧主色变量在新系统里可能是多个语义（按钮 / 指示条 / 大面积 / 图表），按用途拆，不能一对一替换。", properties: ["background", "background-color"], role: "主色 · 按钮填充", to: "color.action.primary" },
  { hints: ["primary-hover", "主色悬停"], note: "", properties: ["background", "background-color"], role: "主色 · 按钮悬停", to: "color.action.primary-hover" },
  { hints: ["indicator", "active-bar", "指示条", "选中条"], note: "", properties: ["background", "background-color", "border-color", "border-left", "border-bottom"], role: "主色 · 指示条", to: "color.brand.indicator" },
  { hints: ["login", "hero", "大面积", "banner"], note: "", properties: ["background", "background-color"], role: "主色 · 大面积", to: "color.bg.brand" },
  { hints: ["chart", "图表", "series"], note: "", properties: ["fill", "stroke", "background"], role: "主色 · 图表", to: "color.chart.1" },
  { hints: ["on-primary", "primary-foreground", "按钮文字"], note: "", properties: ["color"], role: "主按钮文字", to: "color.text.on-primary" },
  { hints: ["success", "成功", "#67c23a", "#52c41a", "#16a34a"], note: "状态色是文字色，配 -bg 浅底；填充只给危险按钮。", properties: ["color", "background", "background-color"], role: "成功", to: "color.status.success" },
  { hints: ["success-bg", "success-light", "成功浅底"], note: "", properties: ["background", "background-color"], role: "成功浅底", to: "color.status.success-bg" },
  { hints: ["warning", "warn", "警示", "#e6a23c", "#faad14", "#d97706"], note: "", properties: ["color", "background", "background-color"], role: "警示", to: "color.status.warning" },
  { hints: ["warning-bg", "warning-light", "警示浅底"], note: "", properties: ["background", "background-color"], role: "警示浅底", to: "color.status.warning-bg" },
  { hints: ["error", "danger-text", "错误", "#f56c6c", "#ff4d4f", "#dc2626"], note: "", properties: ["color", "background", "background-color"], role: "错误", to: "color.status.error" },
  { hints: ["error-bg", "error-light", "错误浅底"], note: "", properties: ["background", "background-color"], role: "错误浅底", to: "color.status.error-bg" },
  { hints: ["info", "提示", "#909399", "#1890ff"], note: "", properties: ["color", "background", "background-color"], role: "信息", to: "color.status.info" },
  { hints: ["info-bg", "info-light"], note: "", properties: ["background", "background-color"], role: "信息浅底", to: "color.status.info-bg" },
  { hints: ["danger", "destructive", "delete", "危险"], note: "配 color.text.on-danger；不要复用 status.error（暗色下会变浅）。", properties: ["background", "background-color"], role: "危险按钮填充", to: "color.action.danger" },
  { hints: ["link", "a-color", "链接", "#409eff", "#1677ff"], note: "链接是否保留色相看 DESIGN；等宽数字型链接不斜体。", properties: ["color"], role: "链接", to: "color.text.link" },
  { hints: ["focus", "ring", "焦点"], note: "", properties: ["outline-color", "box-shadow", "border-color"], role: "焦点环", to: "color.focus.ring" },
  { hints: ["1px"], note: "", properties: ["border-width", "border"], role: "1px 边线宽", to: "border.width.default" },
  { hints: ["4px", "6px", "8px"], note: "按容器层级取 radius.md（控件）或 radius.lg（卡片），不逐像素对应。", properties: ["border-radius"], role: "小圆角（4–8px）", to: "radius.md" },
  { hints: ["12px", "16px"], note: "", properties: ["border-radius"], role: "大圆角（卡片）", to: "radius.lg" },
  { hints: ["14px", "13px", "16px"], note: "尺寸按角色进阶梯；同一个 px 出现在 padding 时另按间距阶梯归。", properties: ["font-size"], role: "正文字号", to: "text.body.size" },
  { hints: ["gap", "间距"], note: "页面级留白只用 space.inline / stack / gutter / card 四个；控件内部用 spacing.*。", properties: ["gap", "margin", "padding"], role: "块间距", to: "space.stack" },
  { hints: ["padding", "内边距"], note: "", properties: ["padding"], role: "卡片内边距", to: "space.card" },
  { hints: ["height", "控件高", "36px", "32px", "40px"], note: "", properties: ["height", "min-height", "line-height"], role: "控件高度", to: "control.height.md" },
  { hints: ["shadow", "阴影", "box-shadow"], note: "阴影拆成 y / blur / color 三件：box-shadow: 0 var(--elevation-card-y) var(--elevation-card-blur) var(--elevation-card-color)。", properties: ["box-shadow"], role: "卡片阴影", to: "elevation.card.color" }
];

/** 生成 migration/roles.json：只保留 semantic 里真实存在的目标；var 名与构建产物一致。 */
export function buildMigrationRoles(systemId, semanticPaths, toCssVariable) {
  const has = (tokenPath) => semanticPaths.has(tokenPath);
  const roles = MIGRATION_ROLES.filter((entry) => has(entry.to)).map((entry) => ({
    hints: entry.hints,
    note: entry.note,
    properties: entry.properties,
    role: entry.role,
    to: entry.to,
    var: `--${toCssVariable(entry.to)}`
  }));
  return {
    description: `旧规范 → ${systemId} 的角色对照（机器可读版，由 web-to-design-system 生成）。migrate --phase settle 起草决策文件时用它：按角色映射，不按色值找最接近的灰。properties 是该角色出现的 CSS 属性上下文；hints 是旧变量名 / 注释里常见的字样——这里只有通用词，请把旧系统独有的变量名与色值补进去。noEquivalent 列旧系统里在新系统没有对应物的东西（如某种深色 hover、淡色选中底）及替代写法，由维护者按 DESIGN.md 填写。`,
    noEquivalent: [
      { legacy: "HTML 内联样式", note: "guard 会把内联字面量算作 Drift。", replacement: "抽成 class 再引用 token", var: null }
    ],
    roles,
    skipped: MIGRATION_ROLES.filter((entry) => !has(entry.to)).map((entry) => entry.to),
    system: systemId,
    version: 1
  };
}

/** 对比度基线的配对：[前景, 底色, 最低比值, 说明]。底色为 null 表示用 bg.surface。 */
export const CONTRAST_PAIRS = [
  ["color.text.primary", "color.bg.page", 4.5, "正文 / 页面底"],
  ["color.text.primary", "color.bg.surface", 4.5, "正文 / 卡片"],
  ["color.text.secondary", "color.bg.surface", 4.5, "次要文字 / 卡片"],
  ["color.text.secondary", "color.bg.page", 4.5, "次要文字 / 页面底"],
  ["color.text.muted", "color.bg.surface", 4.5, "弱化文字 / 卡片"],
  ["color.text.muted", "color.bg.page", 4.5, "弱化文字 / 页面底"],
  ["color.text.muted", "color.bg.subtle", 4.5, "弱化文字 / 浅分区"],
  ["color.text.link", "color.bg.surface", 4.5, "链接 / 卡片"],
  ["color.text.placeholder", "color.bg.input", 3, "占位符 / 输入框（已知例外，≥ 3 即记录）"],
  ["color.text.on-primary", "color.action.primary", 4.5, "主按钮文字 / 填充"],
  ["color.text.on-danger", "color.action.danger", 4.5, "危险按钮文字 / 填充"],
  ["color.text.inverse", "color.bg.inverse", 4.5, "反色文字 / 反色底"],
  ["color.text.on-selected", "color.action.selected", 4.5, "选中块文字 / 选中底"],
  ["color.status.success", "color.status.success-bg", 4.5, "成功胶囊"],
  ["color.status.warning", "color.status.warning-bg", 4.5, "警示胶囊"],
  ["color.status.error", "color.status.error-bg", 4.5, "错误胶囊"],
  ["color.status.info", "color.status.info-bg", 4.5, "信息胶囊"],
  ["color.status.neutral", "color.status.neutral-bg", 4.5, "中性胶囊"],
  ["color.text.danger", "color.bg.surface", 4.5, "危险文字 / 卡片"],
  ["color.icon.default", "color.bg.surface", 3, "独立图标 / 卡片"],
  ["color.icon.muted", "color.bg.surface", 3, "装饰图标 / 卡片"],
  ["color.border.default", "color.bg.page", 1.3, "卡片边线 / 页面底（可辨即可）"],
  ["color.border.input", "color.bg.surface", 1.3, "输入框边线 / 卡片（可辨即可；WCAG UI 组件 3:1 是业界普遍不达的已知例外，Citrine 同样登记为例外）"],
  ["color.border.focus", "color.bg.surface", 3, "焦点边线 / 卡片"],
  ["color.action.primary", "color.bg.surface", 3, "主按钮填充 / 卡片（UI 组件 3:1）"]
];
